---

- hosts: all
  become: true
  tasks:

  - name: Install apache2 and php packages in CentOs and RHEL
    yum:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["CentOS", "Red Hat Enterprise Linux"]

  - name: Install apache2 and php packages in Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
