---

- hosts: all
  become: true
  tasks:

  - name: Install apache and php packages
    ## package is a generic OS package manager
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package  }}"
      state: latest
      update_cache: yes
